name: favorite_places
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
<<<<<<< HEAD
  flutter_map: ^6.1.0
  flutter_riverpod: ^2.5.1
  geocoding: ^3.0.0
  google_fonts: ^6.2.1
  image_picker: ^1.0.7
  latlong2: ^0.9.0
  location: ^5.0.3
  uuid: ^4.3.3
=======
  google_fonts: ^6.2.1
>>>>>>> f7a7267d969019fedb727a6729c0a10eec10dbf1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
